// LCIA reference distributions - 8 baseline programs, per 1 kg cotton lint
// Source: Cotton_GaBi_Model_Comparison_1.xlsx, "Outlier Check - LCIA" tab
const LCIA_REFERENCE = [
  {
    id: 'gwp',
    indicator: 'GWP100 (excl. biogenic CO2)',
    unit: 'kg CO2 eq.',
    n: 8,
    mean: 1.8042,
    stdDev: 0.6853,
    cv: 38,
    lower: 0.4336,
    upper: 3.1748,
    min: 0.817,
    max: 2.8049,
    notes: 'CV=38%. Driven by energy use, N2O, and land use. Moderate spread — flag meaningful.',
    msiUnit: 'GWP pts',
    materiality: 'LOW',
    programs: {
      'BC (India)': 1.9986,
      'Agropima (Peru)': 1.4601,
      'Materra (India)': 0.8170,
      'OCA (India)': 1.6178,
      'BC (China)': 1.6101,
      'BC (Tajikistan)': 2.8049,
      'BC (Pakistan)': 2.7514,
      'BC (Egypt)': 1.3736
    }
  },
  {
    id: 'ep',
    indicator: 'Eutrophication Potential',
    unit: 'kg Phosphate eq.',
    n: 8,
    mean: 0.0673,
    stdDev: 0.0408,
    cv: 60.6,
    lower: 0.0251,
    upper: 0.1490,
    min: 0.0251,
    max: 0.1260,
    notes: 'CV=61%. Driven by N/P fertiliser rates. Borderline high spread — investigate if flagged.',
    msiUnit: 'EP pts',
    materiality: 'HIGH',
    programs: {
      'BC (India)': 0.1120,
      'Agropima (Peru)': 0.0270,
      'Materra (India)': 0.0509,
      'OCA (India)': 0.0251,
      'BC (China)': 0.1260,
      'BC (Tajikistan)': 0.0426,
      'BC (Pakistan)': 0.1069,
      'BC (Egypt)': 0.0480
    }
  },
  {
    id: 'water',
    indicator: 'EF 3.1 Water Use',
    unit: 'm³ world equiv.',
    n: 8,
    mean: 97.04,
    stdDev: 75.5928,
    cv: 77.9,
    lower: 14.9004,
    upper: 248.2257,
    min: 14.9004,
    max: 202.2481,
    notes: 'CV=78%. Dominated by highly irrigated programs (Egypt, Pakistan, Tajikistan). US is largely rainfed — expect a low value.',
    msiUnit: 'WS pts',
    materiality: 'MEDIUM',
    programs: {
      'BC (India)': 21.9861,
      'Agropima (Peru)': 118.0691,
      'Materra (India)': 62.9747,
      'OCA (India)': 14.9004,
      'BC (China)': 24.2516,
      'BC (Tajikistan)': 202.2481,
      'BC (Pakistan)': 174.7374,
      'BC (Egypt)': 157.1522
    }
  },
  {
    id: 'adp',
    indicator: 'Abiotic Depletion - Fossil',
    unit: 'MJ',
    n: 8,
    mean: 17.1991,
    stdDev: 5.4481,
    cv: 31.7,
    lower: 6.3029,
    upper: 28.0953,
    min: 9.5501,
    max: 25.8068,
    notes: 'CV=32%. Most consistent indicator across programs. A flag here is high priority.',
    msiUnit: 'ADP pts',
    materiality: 'LOW',
    programs: {
      'BC (India)': 14.3188,
      'Agropima (Peru)': 15.5153,
      'Materra (India)': 9.5501,
      'OCA (India)': 18.0743,
      'BC (China)': 14.9384,
      'BC (Tajikistan)': 25.8068,
      'BC (Pakistan)': 24.4753,
      'BC (Egypt)': 14.9139
    }
  },
  {
    id: 'bluewater',
    indicator: 'Blue Water Consumption',
    unit: 'kg',
    n: 8,
    mean: 2383.1958,
    stdDev: 1636.9602,
    cv: 68.7,
    lower: 522.6496,
    upper: 5657.1161,
    min: 522.6496,
    max: 4710.6991,
    notes: 'CV=69%. Strongly correlated with irrigation. Low value expected for US Cotton Inc.',
    msiUnit: '—',
    materiality: null,
    programs: {
      'BC (India)': 1309.6982,
      'Agropima (Peru)': 2752.2225,
      'Materra (India)': 1467.5412,
      'OCA (India)': 522.6496,
      'BC (China)': 573.0115,
      'BC (Tajikistan)': 4710.6991,
      'BC (Pakistan)': 4069.8954,
      'BC (Egypt)': 3659.8487
    }
  },
  {
    id: 'eco',
    indicator: 'Ecotoxicity (USEtox 2.12, rec. only)',
    unit: 'CTUe',
    n: 8,
    mean: 74.2507,
    stdDev: 99.4536,
    cv: 133.9,
    lower: 0.1183,
    upper: 273.1579,
    min: 0.1183,
    max: 265.1708,
    notes: 'CV=134%. Extremely high variability driven by pesticide choice. Flags here are weak signal only.',
    msiUnit: '—',
    materiality: null,
    programs: {
      'BC (India)': 120.5759,
      'Agropima (Peru)': 265.1708,
      'Materra (India)': 14.9483,
      'OCA (India)': 0.1183,
      'BC (China)': 3.9713,
      'BC (Tajikistan)': 3.0237,
      'BC (Pakistan)': 19.2566,
      'BC (Egypt)': 166.9406
    }
  }
];

// Inventory parameter reference distributions
// Source: Cotton_GaBi_Model_Comparison_1.xlsx, "Outlier Check - Inventory" tab
const INVENTORY_REFERENCE = [
  {
    parameter: 'N fertiliser rate',
    modelParam: 'FertN_Nitrogen',
    category: 'Fertiliser',
    unit: 'kg N/ha',
    normalisation: 'Direct (kg/ha)',
    n: 3,
    mean: 41.4166,
    stdDev: 49.3894,
    cv: 119.3,
    lower: 8.9,
    upper: 140.1955,
    min: 8.9,
    max: 98.2498,
    notes: 'Synthetic N rate. Note: only 3 programs have this param — interpret flags with caution.',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': 98.2498, 'Pakistan (BC)': 8.9, 'Tajikistan (BC)': null, 'China (BC)': 17.1, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'P fertiliser rate',
    modelParam: 'Fert_Phosphor',
    category: 'Fertiliser',
    unit: 'kg P₂O₅/ha',
    normalisation: 'Direct (kg/ha)',
    n: 6,
    mean: 16.7508,
    stdDev: 13.2517,
    cv: 79.1,
    lower: 1.23,
    upper: 43.2541,
    min: 1.23,
    max: 34.0427,
    notes: 'Phosphorus application rate. Best coverage across reference set (n=6).',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': 34.0427, 'Pakistan (BC)': 8.9, 'Tajikistan (BC)': 1.23, 'China (BC)': 19.3, 'Agropima (Peru)': 30, 'India (BC)': 7.032 }
  },
  {
    parameter: 'K fertiliser rate',
    modelParam: 'Fert_Potas',
    modelParamAlt: 'Fert_Potas_t',
    category: 'Fertiliser',
    unit: 'kg K₂O/ha',
    normalisation: 'Direct (kg/ha)',
    n: 4,
    mean: 73.3195,
    stdDev: 113.7835,
    cv: 155.2,
    lower: 0.11,
    upper: 300.8865,
    min: 0.11,
    max: 240,
    notes: 'Potassium rate. High CV (155%) driven by Agropima outlier (240 kg/ha vs. others ~1–52 kg/ha).',
    lciaDriver: 'Indirect (GWP, ADP)',
    msiScore: 1.48,
    materiality: 'LOW',
    programs: { 'USCTP (US)': 52.3681, 'Pakistan (BC)': 0.8, 'Tajikistan (BC)': 0.11, 'China (BC)': null, 'Agropima (Peru)': 240, 'India (BC)': null }
  },
  {
    parameter: 'Manure application rate',
    modelParam: 'FertN_Manure',
    category: 'Fertiliser',
    unit: 'kg/ha',
    normalisation: 'Direct (kg/ha)',
    n: 4,
    mean: 723.6436,
    stdDev: 684.4821,
    cv: 94.6,
    lower: 80.22,
    upper: 2092.6078,
    min: 80.22,
    max: 1686.88,
    notes: 'Manure enters burden-free in most models. Verify if value seems implausibly high.',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': 643.0743, 'Pakistan (BC)': 484.4, 'Tajikistan (BC)': 80.22, 'China (BC)': 1686.88, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Glyphosate rate',
    modelParam: 'Glyphosate',
    category: 'Pesticide',
    unit: 'kg a.i./ha',
    normalisation: 'Direct (kg/ha)',
    n: 2,
    mean: 1.4366,
    stdDev: 1.9312,
    cv: 134.4,
    lower: 0.071,
    upper: 5.299,
    min: 0.071,
    max: 2.8021,
    notes: 'Only 2 reference programs — statistical bounds very weak. US values typically higher (GM cotton).',
    lciaDriver: 'Chemistry (Ecotox.)',
    msiScore: 3.45,
    materiality: 'MEDIUM',
    programs: { 'USCTP (US)': 2.8021, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': 0.071, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Acephate rate',
    modelParam: 'acephate',
    category: 'Pesticide',
    unit: 'kg a.i./ha',
    normalisation: 'Direct (kg/ha)',
    n: 6,
    mean: 0.2918,
    stdDev: 0.1704,
    cv: 58.4,
    lower: 0.0278,
    upper: 0.6325,
    min: 0.0278,
    max: 0.4489,
    notes: 'Best-covered pesticide parameter across all programs (n=6).',
    lciaDriver: 'Chemistry (Ecotox.)',
    msiScore: 3.45,
    materiality: 'LOW',
    programs: { 'USCTP (US)': 0.4489, 'Pakistan (BC)': 0.4, 'Tajikistan (BC)': 0.3, 'China (BC)': 0.0278, 'Agropima (Peru)': 0.089, 'India (BC)': 0.4 }
  },
  {
    parameter: 'Thidiazuron (PGR) rate',
    modelParam: 'Thidiazuron',
    category: 'Pesticide',
    unit: 'kg a.i./ha',
    normalisation: 'Direct (kg/ha)',
    n: 3,
    mean: 1.2418,
    stdDev: 0.3224,
    cv: 26,
    lower: 0.5969,
    upper: 1.8867,
    min: 0.8804,
    max: 1.5,
    notes: 'PGR used mainly in mechanically-harvested programs. Low CV (26%) — reliable reference.',
    lciaDriver: 'Chemistry (Ecotox.)',
    msiScore: 3.45,
    materiality: 'LOW',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': 1.5, 'Tajikistan (BC)': 0.8804, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Ginning percentage',
    modelParam: 'ginning_percent',
    category: 'Yield',
    unit: 'fraction',
    normalisation: 'Direct (kg/ha)',
    n: 5,
    mean: 0.3795,
    stdDev: 0.0123,
    cv: 3.2,
    lower: 0.3549,
    upper: 0.4041,
    min: 0.37,
    max: 0.4,
    notes: 'Lint fraction of seed cotton. Typical range 0.33–0.44. Very low CV (3%) — reliable flag.',
    lciaDriver: 'Indirect (All indicators)',
    msiScore: null,
    materiality: 'MEDIUM',
    programs: { 'USCTP (US)': 0.38, 'Pakistan (BC)': 0.37, 'Tajikistan (BC)': 0.38, 'China (BC)': 0.4, 'Agropima (Peru)': 0.4, 'India (BC)': null }
  },
  {
    parameter: 'Total N fertiliser / lint',
    modelParam: null,
    computedFrom: { numerator: 'TTL_NFert', denominator: 'O_cottonLint' },
    category: 'Fertiliser',
    unit: 'kg N / kg lint',
    normalisation: 'Per kg lint',
    n: 5,
    mean: 0.3361,
    stdDev: 0.2036,
    cv: 60.6,
    lower: 0.0732,
    upper: 0.7432,
    min: 0.0732,
    max: 0.5182,
    notes: 'Normalised total N. Cotton Inc. value is low vs. reference — consistent with lower-input US system.',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Total fertiliser / lint',
    modelParam: null,
    computedFrom: { numerator: 'TTL_Fert', denominator: 'O_cottonLint' },
    category: 'Fertiliser',
    unit: 'kg / kg lint',
    normalisation: 'Per kg lint',
    n: 5,
    mean: 0.8383,
    stdDev: 0.5464,
    cv: 65.2,
    lower: 0.2968,
    upper: 1.9311,
    min: 0.2968,
    max: 1.6476,
    notes: 'All fertiliser combined. High CV expected. Cotton Inc. at upper range is plausible given dolomite/limestone inputs.',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Total pesticide / lint',
    modelParam: null,
    computedFrom: { numerator: 'TTL_Pesticide', denominator: 'O_cottonLint' },
    category: 'Pesticide',
    unit: 'kg / kg lint',
    normalisation: 'Per kg lint',
    n: 5,
    mean: 0.0022,
    stdDev: 0.0014,
    cv: 62.2,
    lower: 0.0002,
    upper: 0.0049,
    min: 0.0002,
    max: 0.0034,
    notes: 'All pesticide inputs combined. Cotton Inc. value is relatively high — verify herbicide totals.',
    lciaDriver: 'Chemistry (Ecotox.)',
    msiScore: 3.45,
    materiality: 'MEDIUM',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Irrigated water intensity',
    modelParam: null,
    computedFrom: { numerator: 'TTL_IrrigatedWa', denominator: 'O_cottonLint' },
    category: 'Water',
    unit: 'kg water / kg lint',
    normalisation: 'Per kg lint',
    n: 5,
    mean: 3215.8617,
    stdDev: 2133.9208,
    cv: 66.4,
    lower: 687.9135,
    upper: 7483.7033,
    min: 687.9135,
    max: 5675.5811,
    notes: 'US Cotton Inc. expected to be low (largely rainfed). If flagged high, check irrigation data.',
    lciaDriver: 'Water Scarcity',
    msiScore: 20.22,
    materiality: 'LOW',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Diesel energy intensity',
    modelParam: null,
    computedFrom: { numerator: 'TTL_Diesel_i_MJ', denominator: 'O_cottonLint' },
    category: 'Energy',
    unit: 'MJ / kg lint',
    normalisation: 'Per kg lint',
    n: 4,
    mean: 2.9461,
    stdDev: 1.3778,
    cv: 46.8,
    lower: 0.1904,
    upper: 5.7018,
    min: 1.129,
    max: 4.477,
    notes: 'Machinery + irrigation diesel. Note: some reference values flagged as potentially implausible.',
    lciaDriver: 'ADP Fossil',
    msiScore: 0.91,
    materiality: 'LOW',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Total P fertiliser / lint',
    modelParam: null,
    computedFrom: { numerator: 'TTL_Phospho', denominator: 'O_cottonLint' },
    category: 'Fertiliser',
    unit: 'kg P / kg lint',
    normalisation: 'Per kg lint',
    n: 5,
    mean: 0.0128,
    stdDev: 0.0087,
    cv: 67.8,
    lower: 0.0011,
    upper: 0.0301,
    min: 0.0011,
    max: 0.0254,
    notes: 'Cotton Inc. value is notably above reference range — cross-check fertiliser inputs.',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Total K fertiliser / lint',
    modelParam: null,
    computedFrom: { numerator: 'TTL_Potassium', denominator: 'O_cottonLint' },
    category: 'Fertiliser',
    unit: 'kg K / kg lint',
    normalisation: 'Per kg lint',
    n: 5,
    mean: 0.0432,
    stdDev: 0.0473,
    cv: 109.5,
    lower: 0.0001,
    upper: 0.1378,
    min: 0.0001,
    max: 0.1134,
    notes: 'Cotton Inc. value falls within reference range.',
    lciaDriver: 'Indirect (GWP, ADP)',
    msiScore: 1.48,
    materiality: 'LOW',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  },
  {
    parameter: 'Total manure / lint',
    modelParam: null,
    computedFrom: { numerator: 'TTL_Manure', denominator: 'O_cottonLint' },
    category: 'Fertiliser',
    unit: 'kg / kg lint',
    normalisation: 'Per kg lint',
    n: 4,
    mean: 0.5517,
    stdDev: 0.4022,
    cv: 72.9,
    lower: 0.0726,
    upper: 1.3562,
    min: 0.0726,
    max: 1.0493,
    notes: 'Manure enters burden-free. Cotton Inc. value is within expected range.',
    lciaDriver: 'Eutrophication (EP)',
    msiScore: 184.23,
    materiality: 'HIGH',
    programs: { 'USCTP (US)': null, 'Pakistan (BC)': null, 'Tajikistan (BC)': null, 'China (BC)': null, 'Agropima (Peru)': null, 'India (BC)': null }
  }
];

// GaBi → Model parameter name mappings
// These are confirmed mappings from the comparison file
const NAME_MAPPINGS = {
  'TTL_Diesel_m_MJ': { modelParam: 'TTL_Diesel_i_MJ', note: "GaBi name mapped to model param 'TTL_Diesel_i_MJ'" },
  'P_LDPEfilm': { modelParam: 'P_LDPE_1', note: "GaBi name mapped to model param 'P_LDPE_1'" },
  'TTL_Fert_Min_Gy': { modelParam: 'TTL_Fert_Mineral_Gypsum', note: "GaBi name mapped to model param 'TTL_Fert_Mineral_Gypsum'" },
  'TTL_Fert_Min_Bo': { modelParam: 'TTL_Fert_Mineral_Boron', note: "GaBi name mapped to model param 'TTL_Fert_Mineral_Boron'" },
  'TTL_Organic_P': { modelParam: 'organic_P', note: "GaBi name mapped to model param 'organic_P'" },
  'TTL_Pesticide_u': { modelParam: 'TTL_Pesticide_unspec', note: "GaBi name mapped to model param 'TTL_Pesticide_unspec'" },
  'Chlorothal_s': { modelParam: 'Chlorothalonil_s', note: "GaBi name mapped to model param 'Chlorothalonil_s'" },
  'Chlorothal_a': { modelParam: 'Chlorothalonil_a', note: "GaBi name mapped to model param 'Chlorothalonil_a'" },
  'Chlorothal_w': { modelParam: 'Chlorothalonil_w', note: "GaBi name mapped to model param 'Chlorothalonil_w'" }
};

// Known NOT TRACKED pesticide patterns (GaBi pesticide params with no model equivalent)
// These appear in the GaBi export but are zero and have no matching model parameter
const NOT_TRACKED_PATTERNS = [
  '_a', '_s', '_w'  // Pesticide emission suffixes for zero-value pesticides
];
